# Generated by Django 5.1 on 2024-08-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
