# Generated by Django 5.1 on 2024-09-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0004_alter_slot_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultation_app.slot', verbose_name='Слот'),
        ),
    ]
