# Generated by Django 5.1 on 2024-09-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0005_alter_consultation_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Ожидает'), ('Accepted', 'Принят'), ('Rejected', 'Отклонён')], db_index=True, default='Pending', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(db_index=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(db_index=True, verbose_name='Начало'),
        ),
    ]
