# Generated by Django 5.1 on 2024-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0006_alter_consultation_status_alter_slot_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
    ]
